name = "api"
compatibility_date = "2023-01-01"

[ai]
binding = "AI"

[env.development]
# 開発環境の設定
name = "A23z1jk@aiit.ac.jp's Account"
account_id = "fe0e2e0a728e9d93d702cd8e1f253f2a"

[env.production]
# 本番環境の設定
name = "M.s.1123.aqui@gmail.com's Account"
account_id = "6299d8b48d06d8d4c15d981093507f68"

# [vars]
# MY_VARIABLE = "production_value"

[[kv_namespaces]]
binding = "NEWS_ON_EARTH"
id = "b3f81eb696a44abdb3db05396d9d9ef4"
#kv_namespaces = [
#    { binding = "NEWS_ON_EARTH", id = "b3f81eb696a44abdb3db05396d9d9ef4" }
#]

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
