name: Deploy Worker

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Set Environment Variable in Wrangler
        run: |
          echo "$NEWS_API_KEY" | wrangler secret put NEWS_API_KEY
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

      - name: Install Dependencies
        run: yarn install
        working-directory: api

      - name: Deploy
        run: |
          yarn deploy
        working-directory: api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKERS_TOKEN_DEV }}
