name: Deploy Functions

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Functions
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_DEV }}
          workingDirectory: "functions"
