name: Deploy to Cloudflare

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install & Build
      run: |
        cd path/to/your/directory
        yarn install
        yarn start

    - name: Deploy to Cloudflare
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        environment: 'production'
