name: Deploy Wrangler

on:
  push:
    branches: [ development ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_DEV }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_DEV }}
          workingDirectory: "news-on-earth"
